Jeff sabrina will
muzny/csci3010-spring2019-collab pull request #16
Opened 2019-02-07 18:46 UTC by wian5430

I want to merge my code with master

2019-02-07 19:48 UTC, bensont commented on utility_functions/main.cpp
> +std::vector<int> VectorPlusN(v, 5);
This should be included in main so the test runs. Also, std::vector<int> VectorPlusN(v, 5); is invalid syntax.
VectorPlusN() has a return that has not been instantiated. Use td::vector<int> returned_vector = VectorPlusN(v, 5);

2019-02-07 19:48 UTC, bensont commented on utility_functions/main.cpp
> +    Sum(7,10);
This has a return that isn't accounted for. Collect the return and print the result as well as the sent numbers to Sum()

2019-02-07 19:49 UTC, bensont requested changes
Compilation Error:

main.cpp:10:30: error: ‘std::vector<int> VectorPlusN’ redeclared as different kind of symbol
 std::vector<int> VectorPlusN(v, 5);
                              ^
In file included from main.cpp:1:0:
ManyFunctions.h:20:18: note: previous declaration ‘std::vector<int> VectorPlusN(std::vector<int>, int)’
 std::vector<int> VectorPlusN(std::vector<int> v, int n);

The declaration in main should be changed.
Also, the main doesn't show any output to confirm that the function runs correctly.

2019-02-12 19:30 UTC, muzny requested changes
Please make the changes that Tyler requested by class on 2/19.

2019-03-12 03:23 UTC, sabrinatouchCU commented
I want to merge my code with master

2019-03-12 05:13 UTC, bensont approved these changes

2019-03-12 14:03 UTC, muzny approved these changes
Looks good!

2019-03-13 01:23 UTC, merged